### ISSUE TITLE
Open mulitple mini-app

### ISSUE THREAD

**Issue by toastyy00** [RGB-Outl4w/ThePixelsAutoReloaded#3]
Can I run 2 bots at once, like I want to open Catizen and The Pixels on my Telegram Desktop without having to close one of them?

**Comment by RGB-Outl4w** [comment]
Hello. Unfortunately, you cannot do this in a single Telegram Desktop client as it only allows one web app opened at a time per account, 3 web apps per client at a time in total (_probably 4 with premium_).

**However**, no one is stopping you from cloning your Telegram Desktop client and getting 3 more available web apps for the same, or different accounts. You can use [this guide](https://youtu.be/sw1mRJQi7nM?si=uwwRyRnOBiZiAQaP) and see if it works.

Please note that running too many different accounts on one IP/machine at the same time can get you accused of botting and get your accounts banned. Everything has its limit.

**Comment by toastyy00** [comment]
> Hello. Unfortunately, you cannot do this in a single Telegram Desktop client as it only allows one web app opened at a time per account, 3 web apps per client at a time in total (_probably 4 with premium_).
> 
> **However**, no one is stopping you from cloning your Telegram Desktop client and getting 3 more available web apps for the same, or different accounts. You can use [this guide](https://youtu.be/sw1mRJQi7nM?si=uwwRyRnOBiZiAQaP) and see if it works.
> 
> Please note that running too many different accounts on one IP/machine at the same time can get you accused of botting and get your accounts banned. Everything has its limit.

Thank you for the response, I have successfully cloned my Telegram. 
Is The Pixels script still working? I tried after entering the command in the console, all that happened was a blank screen on the bot, the bot didn't load

**Comment by RGB-Outl4w** [comment]
> > Hello. Unfortunately, you cannot do this in a single Telegram Desktop client as it only allows one web app opened at a time per account, 3 web apps per client at a time in total (_probably 4 with premium_).
> > **However**, no one is stopping you from cloning your Telegram Desktop client and getting 3 more available web apps for the same, or different accounts. You can use [this guide](https://youtu.be/sw1mRJQi7nM?si=uwwRyRnOBiZiAQaP) and see if it works.
> > Please note that running too many different accounts on one IP/machine at the same time can get you accused of botting and get your accounts banned. Everything has its limit.
> 
> Thank you for the response, I have successfully cloned my Telegram. Is The Pixels script still working? I tried after entering the command in the console, all that happened was a blank screen on the bot, the bot didn't load

I'm glad this helped. I don't think that The Pixels project belongs to this discussion, but let this time be an exception. There seemed to be a problem with accessing a bundle in The Pixels launcher, I've switched it to an alternative one. Let it a couple minutes to synchronize and it'll start doing its job. Sadly, it has a couple of visual bugs, but its technical purpose is still the same.

Since the main problem of this issue is solved, I'm now closing this thread.
